# The rest of my fun git aliases
alias gam="git commit --amend"
alias gar="git-addremove"
alias gci="git commit"
alias gd="git diff"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gm="git merge"
alias gpp="git pull && git push"
alias gr="git rebase"
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
alias gsb="git status -sb" # upgrade your git if -sb breaks for you. it's fun.
alias gsci="git svn dcommit"
alias gsf="git svn fetch"
alias gsup="git svn rebase"

#alias gl="git pull --prune"
#alias gp="git push origin HEAD"
#alias gc="git commit"
#alias gca="git commit -a"
#alias gco="git checkout"
#alias gb="git branch"
